/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Application implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "APPLICATION_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "APPLICATION_ID_SEQ", name = "APPLICATION_ID_GENERATOR")
   private Long id;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label(value = "Applicant")
   private Applicant applicant;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label(value = "Property")
   private Property property;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label(value = "Appraisal")
   private Appraisal appraisal;

   @org.kie.api.definition.type.Label(value = "Down Payment")
   private Integer downPayment;

   @org.kie.api.definition.type.Label(value = "Mortgage Amortization")
   private Integer amortization;

   @org.kie.api.definition.type.Label(value = "Mortgage Amount")
   private Integer mortgageAmount;

   @org.kie.api.definition.type.Label(value = "Mortgage Interest APR")
   private Double apr;

   @javax.persistence.OneToMany(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label(value = "Validation Errors")
   private java.util.List<com.redhat.bpms.examples.mortgage.ValidationError> validationErrors;

   public Application()
   {
   }

   public Long getId()
   {
      return this.id;
   }

   public void setId(Long id)
   {
      this.id = id;
   }

   public Applicant getApplicant()
   {
      return this.applicant;
   }

   public void setApplicant(
         Applicant applicant)
   {
      this.applicant = applicant;
   }

   public Property getProperty()
   {
      return this.property;
   }

   public void setProperty(Property property)
   {
      this.property = property;
   }

   public Appraisal getAppraisal()
   {
      return this.appraisal;
   }

   public void setAppraisal(
         Appraisal appraisal)
   {
      this.appraisal = appraisal;
   }

   public Integer getDownPayment()
   {
      return this.downPayment;
   }

   public void setDownPayment(Integer downPayment)
   {
      this.downPayment = downPayment;
   }

   public Integer getAmortization()
   {
      return this.amortization;
   }

   public void setAmortization(Integer amortization)
   {
      this.amortization = amortization;
   }

   public Integer getMortgageAmount()
   {
      return this.mortgageAmount;
   }

   public void setMortgageAmount(Integer mortgageAmount)
   {
      this.mortgageAmount = mortgageAmount;
   }

   public Double getApr()
   {
      return this.apr;
   }

   public void setApr(Double apr)
   {
      this.apr = apr;
   }

   public java.util.List<com.redhat.bpms.examples.mortgage.ValidationError> getValidationErrors()
   {
      return this.validationErrors;
   }

   public void setValidationErrors(
         java.util.List<com.redhat.bpms.examples.mortgage.ValidationError> validationErrors)
   {
      this.validationErrors = validationErrors;
   }

   public Application(
         Long id,
         Applicant applicant,
         Property property,
         Appraisal appraisal,
         Integer downPayment,
         Integer amortization,
         Integer mortgageAmount,
         Double apr,
         java.util.List<com.redhat.bpms.examples.mortgage.ValidationError> validationErrors)
   {
      this.id = id;
      this.applicant = applicant;
      this.property = property;
      this.appraisal = appraisal;
      this.downPayment = downPayment;
      this.amortization = amortization;
      this.mortgageAmount = mortgageAmount;
      this.apr = apr;
      this.validationErrors = validationErrors;
   }

}